import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{margin: "0", padding: "0"}}>
        <header>
          <nav style={{
            padding: "0",
          }}>
            <ul style={{
              display: "flex",
              gap: "40px",
              listStyle: "none",
              margin: "0",
              padding: "20px",
              backgroundColor: "lightblue"
            }}>
              <li>
                <Link style={{ textDecoration: "none", color: "black", backgroundColor: "white", padding: "10px", borderRadius: "8px" }} href="/">Home</Link>
              </li>
              {/* <li>
                <Link  style={{ textDecoration: "none", color: "black", backgroundColor: "white", padding: "10px", borderRadius: "8px" }} href="/products">Products</Link>
              </li> */}
              <li>
                <Link  style={{ textDecoration: "none", color: "black", backgroundColor: "white", padding: "10px", borderRadius: "8px" }} href="/profile">Profile</Link>
              </li>
              <li>
                <Link  style={{ textDecoration: "none", color: "black", backgroundColor: "white", padding: "10px", borderRadius: "8px" }} href="/login">Login</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main style={{
          padding: "10px",
        }}>{children}</main>
        <footer style={{
          borderTop: "1px solid black",
          textAlign: "center"
        }}>
          <p>Copyright 2023 EJP</p>
        </footer>
      </body>
    </html>
  )
}

