import Link from "next/link"
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { LoginLink, LogoutLink } from "@kinde-oss/kinde-auth-nextjs/components";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { getUser } = getKindeServerSession();
  const user = await getUser();
  // console.log(user);

  return (
    <html lang="en">
      <body style={{ margin: "0", padding: "0" }} cz-shortcut-listen="true">
        <header>
          <nav style={{
            padding: "0",
          }}>
            <ul style={{
              display: "flex",
              gap: "40px",
              listStyle: "none",
              margin: "0",
              padding: "20px",
              backgroundColor: "lightblue"
            }}>
              <li>
                <Link style={{ textDecoration: "none", color: "black", backgroundColor: "white", padding: "10px", borderRadius: "8px" }} href="/">Home</Link>
              </li>
              {
                user ?
                  <li>
                    <Link style={{ textDecoration: "none", color: "black", backgroundColor: "white", padding: "10px", borderRadius: "8px" }} href="/profile">Profile</Link>
                  </li> :
                  <li>
                    <LoginLink>
                      <button style={{ textDecoration: "none", color: "black", backgroundColor: "white", padding: "10px", borderRadius: "8px" }}>Profile</button>
                    </LoginLink>
                  </li>
              }
              {
                (user) ?
                  <li>
                    <LogoutLink>
                      <button style={{ textDecoration: "none", color: "black", backgroundColor: "white", padding: "10px", borderRadius: "8px" }}>Logout</button>
                    </LogoutLink>
                  </li> :
                  <li>
                    <LoginLink>
                      <button style={{ textDecoration: "none", color: "black", backgroundColor: "white", padding: "10px", borderRadius: "8px" }}>Login</button>
                    </LoginLink>
                  </li>
              }
            </ul>
          </nav>
        </header>
        <main style={{
          padding: "10px",
        }}>{children}</main>
        <footer style={{
          borderTop: "1px solid black",
          textAlign: "center"
        }}>
          <p>Copyright 2023 EJP</p>
        </footer>
      </body>
    </html>
  )
}

